# Generated by Django 2.0.7 on 2018-09-12 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=500)),
                ('related_to', models.CharField(max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job.Job')),
            ],
            options={
                'db_table': 'deal',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
