# Generated by Django 2.0.7 on 2018-09-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='location',
            new_name='tag',
        ),
    ]
