# Generated by Django 2.0.7 on 2018-09-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('pic', models.FileField(upload_to='Jobdocuments/')),
                ('password', models.CharField(max_length=50)),
                ('calendar_url', models.TextField(blank=True, null=True)),
                ('is_admin', models.NullBooleanField()),
                ('is_account_owner', models.NullBooleanField()),
                ('is_disabled', models.NullBooleanField()),
                ('schedule_id', models.CharField(max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
