# Generated by Django 2.0.7 on 2018-09-22 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='Owner',
        ),
    ]
