# Generated by Django 2.0.7 on 2018-09-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('job_location', models.CharField(max_length=500)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_location', models.CharField(max_length=500)),
                ('architect', models.TextField(blank=True, null=True)),
                ('engineer_name', models.CharField(max_length=255)),
                ('contractor_customer', models.CharField(max_length=500)),
                ('file_upload', models.FileField(upload_to='Jobdocuments/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
